# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 320, 61, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 30, 81, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 60, 81, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 90, 81, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 120, 81, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 190, 211, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 150, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 30, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 60, 31, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 90, 31, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 120, 31, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 365, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.lineEdits = [self.lineEdit, self.lineEdit_2, self.lineEdit_3, self.lineEdit_4]
        for elem in self.lineEdits:
            elem.setEnabled(False)
        self.pushButton.clicked.connect(self.order)
        self.checkBoxes = [self.checkBox, self.checkBox_2, self.checkBox_3, self.checkBox_4]
        self.checkBox.clicked.connect(self.checkBaseCount)
        self.checkBox_2.clicked.connect(self.checkBaseCount)
        self.checkBox_3.clicked.connect(self.checkBaseCount)
        self.checkBox_4.clicked.connect(self.checkBaseCount)
        self.checkBox.price = 60
        self.checkBox_2.price = 50
        self.checkBox_3.price = 100
        self.checkBox_4.price = 80

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "Чизбургер"))
        self.checkBox_2.setText(_translate("MainWindow", "Гамбургер"))
        self.checkBox_3.setText(_translate("MainWindow", "Кока-кола"))
        self.checkBox_4.setText(_translate("MainWindow", "Наггетсы"))
        self.pushButton.setText(_translate("MainWindow", "Заказать"))
        self.checkBoxes = [self.checkBox, self.checkBox_2, self.checkBox_3, self.checkBox_4]

    def checkBaseCount(self):
        if MainWindow.sender().isChecked():
            if MainWindow.sender() == self.checkBox:
                self.lineEdit.setEnabled(True)
                self.lineEdit.count = 1
                self.lineEdit.setText('1')
            elif MainWindow.sender() == self.checkBox_2:
                self.lineEdit_2.setEnabled(True)
                self.lineEdit_2.count = 1
                self.lineEdit_2.setText('1')
            elif MainWindow.sender() == self.checkBox_3:
                self.lineEdit_3.setEnabled(True)
                self.lineEdit_3.count = 1
                self.lineEdit_3.setText('1')
            else:
                self.lineEdit_4.setEnabled(True)
                self.lineEdit_4.count = 1
                self.lineEdit_4.setText('1')
        else:
            if MainWindow.sender() == self.checkBox:
                self.lineEdit.setText('')
                self.lineEdit.setEnabled(False)
            elif MainWindow.sender() == self.checkBox_2:
                self.lineEdit_2.setText('')
                self.lineEdit_2.setEnabled(False)
            elif MainWindow.sender() == self.checkBox_3:
                self.lineEdit_3.setText('')
                self.lineEdit_3.setEnabled(False)
            else:
                self.lineEdit_4.setText('')
                self.lineEdit_4.setEnabled(False)

    def order(self):
        numbers = [int(line.text()) for line in self.lineEdits if line.isEnabled()]
        positions = list(filter(lambda elem: elem.isChecked(), self.checkBoxes))

        res = []
        for i in range(len(numbers)):
            res.append(f'{positions[i].text()}-----{numbers[i]}-----{numbers[i] * positions[i].price}')
        res = '\n'.join(res)
        self.plainTextEdit.setPlainText(f'Ваш заказ:\n\n{res}')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
